#!/bin/bash 
function mysqlDbIsDown { mysqladmin -h $1 -u $2 --password=$3 status > /dev/null 2>&1 && echo "$?"; }

while [ -z $(mysqlDbIsDown db root password)  ]; do
    echo "waiting for application db to start working"
    sleep 3s
done

while [ -z $(mysqlDbIsDown unitedwaydb root password)  ]; do
    echo "waiting for unitedway db to start working"
    sleep 3s
done

mysql --host=unitedwaydb --user=root --password=password << EOF
CREATE DATABASE IF NOT EXISTS ${UNITEDWAYDB_DATABASE};

CREATE USER IF NOT EXISTS '${UNITEDWAYDB_USERNAME}'@'%' IDENTIFIED BY '${UNITEDWAYDB_PASSWORD}';
GRANT SELECT ON  ${UNITEDWAYDB_DATABASE} . * TO   '${UNITEDWAYDB_USERNAME}'@'%';

USE ${UNITEDWAYDB_DATABASE};

CREATE TABLE IF NOT EXISTS document_assigned_index ( caseid varchar(20) not null, document_type varchar(20) not null, index_date datetime not null );
CREATE TABLE IF NOT EXISTS impact_indexed ( caseid varchar(20) not null, document_type varchar(20) not null, index_date datetime not null );
EOF

# Remove a potentially pre-existing server.pid for Rails. This is a known issue.
rm -f /app/tmp/pids/server.pid

bin/rails db:setup
bin/rails server --port 3001 --binding 0.0.0.0