#!/bin/bash 
function dbIsDown { mysqladmin -h db -u root --password=password status  > /dev/null 2>&1 && echo "$?"; }
while [ -z $(dbIsDown)  ]; do
    echo "waiting for application db to start working"
    sleep 3s
done

function dbIsDown { mysqladmin -h unitedwaydb -u root --password=password status  > /dev/null 2>&1 && echo "$?"; }
while [ -z $(dbIsDown)  ]; do
    echo "waiting for unitedway db to start working"
    sleep 3s
done

mysql --host=unitedwaydb --user=root --password=password < unitedway_db_setup.sql

# Remove a potentially pre-existing server.pid for Rails. This is a known issue.
rm -f /app/tmp/pids/server.pid

bin/rails db:setup
bin/rails server --port 3001 --binding 0.0.0.0