#!/bin/bash 

git clone https://github.com/ctoec/care-4-kids-auto-notifier.git /tmp/care-4-kids-auto-notifier
cd /tmp/care-4-kids-auto-notifier
source /home/rails/railsapps/care-4-kids-auto-notifier/shared/.env
SERVER_IP=$SERVER_IP SERVER_PASSWORD=$SERVER_PASSWORD RAILS_ENV=production cap production deploy --trace
rm -rf /tmp/care-4-kids-auto-notifier
