#!/bin/bash 

git clone https://github.com/ctoec/care-4-kids-auto-notifier.git /tmp/care-4-kids-auto-notifier
cp /home/rails/railsapps/care-4-kids-auto-notifier/shared/.env /tmp/care-4-kids-auto-notifier/.env
cd /tmp/care-4-kids-auto-notifier
bundle install
SERVER_IP=127.0.0.1 RAILS_ENV=production cap production deploy --trace
cd /tmp
rm -rf /tmp/care-4-kids-auto-notifier