#!/bin/bash 

set -ex

# Remove a potentially pre-existing server.pid for Rails. This is a known issue.
rm -f /app/tmp/pids/server.pid

bundle update

./scripts/setupRailsDatabase 
./scripts/setupUWDatabase

bin/rails server --port 3001 --binding 0.0.0.0