#!/bin/bash 
function mysqlDbIsDown { mysqladmin -h $1 -u $2 --password=$3 status > /dev/null 2>&1 && echo "$?"; }

while [ -z $(mysqlDbIsDown db root password)  ]; do
    echo "waiting for application db to start working"
    sleep 3s
done

while [ -z $(mysqlDbIsDown unitedwaydb root password)  ]; do
    echo "waiting for unitedway db to start working"
    sleep 3s
done

set -ex

# Remove a potentially pre-existing server.pid for Rails. This is a known issue.
rm -f /app/tmp/pids/server.pid

bundle update

./scripts/setupRailsDatabase 
./scripts/setupUWDatabase

bin/rails server --port 3001 --binding 0.0.0.0