#!/bin/bash 

set -ex

# Remove a potentially pre-existing server.pid for Rails. This is a known issue.
rm -f /app/tmp/pids/server.pid

./scripts/setupRailsDatabase
./scripts/setupUWDatabase

bundle

RAILS_ENV=${RAILS_ENV:-development} bin/delayed_job run