#!/bin/bash

mysql --host=$UNITEDWAYDB_HOST --user=$UNITEDWAYDB_ADMIN_USERNAME --password=$UNITEDWAYDB_ADMIN_PASSWORD << EOF
CREATE DATABASE IF NOT EXISTS ${UNITEDWAYDB_DATABASE};

CREATE USER IF NOT EXISTS '${UNITEDWAYDB_USERNAME}'@'%' IDENTIFIED BY '${UNITEDWAYDB_PASSWORD}';
GRANT SELECT ON  ${UNITEDWAYDB_DATABASE} . * TO   '${UNITEDWAYDB_USERNAME}'@'%';

USE ${UNITEDWAYDB_DATABASE};

CREATE TABLE IF NOT EXISTS document_assigned_index ( caseid varchar(20) not null, document_type varchar(20) not null, index_date datetime not null );
CREATE TABLE IF NOT EXISTS impact_indexed ( caseid varchar(20) not null, document_type varchar(20) not null, index_date datetime not null );
EOF